- include_vars: "{{ ansible_os_family }}.yml"

- name: Create /opt/kubernetes-offline dir
  file:
    path: /opt/kubernetes-offline
    state: directory

- name: Cleanup /opt/kubernetes-offline dir
  file:
    path: /opt/kubernetes-offline/{{ item }}
    state: absent
  with_items:
    - rpms
    - debs

- name: Transfer all offline file
  copy:
    src: "{{ item }}"
    dest: /opt/kubernetes-offline
  with_fileglob:
    - ./offline-files/*

- name: Unarchive files
  unarchive:
    src: /opt/kubernetes-offline/{{ item }}
    dest: /opt/kubernetes-offline/
    remote_src: yes
  with_items:
    - "{{ k8s_offline_repo_tarball }}"
    - container-images.tar.gz

- include_tasks: "{{ ansible_os_family }}.yml"
