- name: Clear /opt/kubernetes-offline dir
  file:
    path: /opt/kubernetes-offline
    state: absent

- name: Create /opt/kubernetes-offline dir
  file:
    path: /opt/kubernetes-offline
    state: directory

- name: Transfer k8s-offline-repo
  unarchive:
    src: ./offline-files/{{ item }}
    dest: /opt/kubernetes-offline/
  with_items:
    - k8s-offline-repo.tar.gz
    - k8s-images.tar.gz

- name: Transfer calico.yml
  copy:
    src: ./offline-files/calico.yaml
    dest: /opt/kubernetes-offline

- name: Install offline yum repo
  copy:
    src: kubernetes-offline.repo
    dest: /etc/yum.repos.d/

# install yum-plugin-versionlock (dirty hack...)
- name: Install yum-plugin-versionlock
  shell: rpm -Uvh /opt/kubernetes-offline/rpms/yum-plugin-versionlock-*.rpm || exit 0
