- include_vars: "{{ ansible_os_family }}.yml"

- name: Clear /opt/kubernetes-offline dir
  file:
    path: /opt/kubernetes-offline
    state: absent

- name: Create /opt/kubernetes-offline dir
  file:
    path: /opt/kubernetes-offline
    state: directory

- name: Transfer k8s-offline-repo
  unarchive:
    src: ./offline-files/{{ item }}
    dest: /opt/kubernetes-offline/
  with_items:
    - "{{ k8s_offline_repo_tarball }}"
    - k8s-images.tar.gz

- name: Transfer calico.yml
  copy:
    src: ./offline-files/calico.yaml
    dest: /opt/kubernetes-offline

- include_tasks: "{{ ansible_os_family }}.yml"
