- name: Install offline yum repo
  copy:
    src: kubernetes-offline.repo
    dest: /etc/yum.repos.d/

# install yum-plugin-versionlock (dirty hack...)
- name: Install yum-plugin-versionlock
  shell: rpm -Uvh /opt/kubernetes-offline/rpms/yum-plugin-versionlock-*.rpm || exit 0
