- name: Update apt cache
  apt:
    update_cache: yes

- name: Install common packages
  apt:
    name:
      #- selinux-utils
      #- python-selinux
      - nfs-common
      - nfs-kernel-server
    state: present
