- name: Update apt cache
  apt:
    update_cache: yes

#- name: Install python cryptography
#  apt:
#    name: python-cryptography
#    state: present
#    update_cache: "{{ offline_install | bool == False }}"

#- name: Install selinux-utils, python-selinux (ubuntu)
#  apt:
#    name:
#      - selinux-utils
#      - python-selinux
#    state: latest
