- include_tasks: "{{ ansible_os_family }}.yml"

- name: Disable swap
  command: swapoff -a

- name: Disable swap in /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Install /etc/sysctl.d/k8s.conf
  copy:
    src: sysctl-k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: Add module loader
  copy:
    src: container-modules.conf
    dest: /etc/modules-load.d/
    owner: root
    group: root
  notify: load_modules

- name: sysctl
  command: sysctl --system

- import_tasks: cfssl.yml
