- name: Enable rhel-7-server-extras-rpms
  shell: subscription-manager repos --enable=rhel-7-server-extras-rpms
  when: ansible_distribution == "RedHat"

- name: Install libselinux-python (rhel)
  yum:
    name: libselinux-python
    state: latest
    enablerepo: "{{ yum_enablerepo }}"
    disablerepo: "{{ yum_disablerepo }}"
  when: ansible_distribution in [ "RedHat", "CentOS" ]

#- name: Install selinux-utils, python-selinux (ubuntu)
#  apt:
#    name:
#      - selinux-utils
#      - python-selinux
#    state: latest
#  when: ansible_distribution in [ "Ubuntu" ]

- name: Disable SELinux
  selinux:
    state: disabled
  when: ansible_distribution in [ "RedHat", "CentOS" ]

- name: Disable swap
  shell: swapoff -a

- name: Disable swap in /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Install /etc/sysctl.d/k8s.conf
  copy:
    src: sysctl-k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: sysctl
  shell: sysctl --system
