- name: Enable rhel-7-server-extras-rpms
  command: subscription-manager repos --enable=rhel-7-server-extras-rpms
  when: ansible_distribution == "RedHat"

- name: Install common packages (rhel)
  yum:
    name:
      - libselinux-python
      - lvm2
      - gnupg2
      - nfs-utils
      - rpcbind
    state: latest
    enablerepo: "{{ yum_enablerepo }}"
    disablerepo: "{{ yum_disablerepo }}"

- name: Disable SELinux
  selinux:
    state: disabled
