- name: Enable rhel-7-server-extras-rpms
  command: subscription-manager repos --enable=rhel-7-server-extras-rpms
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"

- include_vars: "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"

- name: Install common packages (rhel)
  yum:
    name: "{{ preinstall_dependencies }}"
    state: latest
    enablerepo: "{{ yum_enablerepo }}"
    disablerepo: "{{ yum_disablerepo }}"

- name: Disable SELinux
  selinux:
    state: disabled

- name: Add br_netfilter.modules
  copy:
    src: br_netfilter.modules
    dest: /etc/sysconfig/modules/
    owner: root
    group: root
    mode: 0755

- name: Modprobe br_netfilter
  shell:
    cmd: /etc/sysconfig/modules/br_netfilter.modules
