- name: Load config files
  slurp:
    path: "{{ registry_config_dir }}/{{ item }}"
  register: slurp_file
  with_items:
    - registry.crt
    - registry.key

#- debug:
#    msg: "{{ item.content | b64decode }}"
#  with_items: "{{ slurp_file.results }}"

- set_fact:
    registry_crt_content: "{{ slurp_file.results[0].content }}"
    registry_key_content: "{{ slurp_file.results[1].content }}"
  
- name: Install registry pod manifest
  template:
    src: "{{ item.src }}"
    dest: "{{ registry_config_dir }}/{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: registry-pv-based.yml.j2, dest: registry.yml, mode: "0600" }
    - { src: registry-configmap.yml.j2, dest: configmap.yml, mode: "0600" }

- name: Apply registry pod manifest
  shell: kubectl apply -f {{ registry_config_dir }}/{{ item }} --kubeconfig /etc/kubernetes/admin.conf
  with_items:
    - configmap.yml
    - registry.yml
