# Create htpasswd
# Note: do not use ansible htpassword module
- name: Create htpasswd
  shell:
    cmd: docker run --rm --entrypoint htpasswd registry:{{ registry_version }} -Bbn {{ registry_user }} {{ registry_password }} > htpasswd
    chdir: "{{ registry_config_dir }}"

- name: Change htpasswd mode
  file:
    path: "{{ registry_config_dir }}/htpasswd"
    owner: root
    mode: 0600

- name: Create {{ registry_data_dir }} dirs
  file:
    path: "{{ registry_data_dir }}"
    state: directory

- name: Install registry static pod manifest
  template:
    src: static-pod/registry.yml.j2
    dest: /etc/kubernetes/manifests/registry.yml

- name: Allow firewall for registry
  firewalld:
    port: "{{ registry_port }}"
    permanent: yes
    state: enabled
    immediate: yes
  when: firewall_enabled
