- name: create ~/.kube
  file:
    path: .kube/
    state: directory
  become: no

- name: copy admin.conf to ~/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: .kube/config
    owner: "{{ ansible_user_id }}"
    mode: 0600
    remote_src: true
  become: yes
