apiVersion: v1
kind: Pod
metadata:
  name: registry
  namespace: kube-system
  labels:
    component: registry
spec:
  containers:
    - name: registry
      image: registry:2
      imagePullPolicy: IfNotPresent
      env:
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /config/htpasswd
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /config/registry.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /config/registry.key
      volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
        - name: registry-config
          mountPath: /config
  hostNetwork: true
  volumes:
    - name: registry-data
      hostPath:
        path: /var/lib/registry/data
        type: Directory
    - name: registry-config
      hostPath:
        path: /var/lib/registry/config
        type: Directory
