- name: Install libselinux-python
  yum:
    name: libselinux-python
    state: latest
    enablerepo: "{{ yum_enablerepo }}"
    disablerepo: "{{ yum_disablerepo }}"

- name: Disable SELinux
  selinux:
    state: disabled

- name: Disable swap
  shell: swapoff -a

- name: Disable swap in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+.*)$'
    replace: '# \1'

- name: Install /etc/sysctl.d/k8s.conf
  copy:
    src: sysctl-k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: sysctl
  shell: sysctl --system
