- name: Create config dir
  file:
    path: "{{ ingress_nginx_config_dir }}"
    state: directory

- name: Copy deployment yaml
  copy:
    src: deploy.yaml
    dest: "{{ ingress_nginx_config_dir }}"

- name: Apply deployment yaml
  shell:
    cmd: kubectl apply -f {{ ingress_nginx_config_dir }}/deploy.yaml --kubeconfig=/etc/kubernetes/admin.conf
