- name: Copy get-join-files.sh
  copy:
    src: get-join-files.sh
    dest: /tmp/get-join-files.sh
    mode: 0755

- name: Execute get-join-files.sh
  command: /tmp/get-join-files.sh

- name: Fetch files
  fetch:
    src: /tmp/{{ item }}
    dest: ./files/
    flat: yes
  with_items:
    #- join-files.tar.gz
    - join.sh
    - certificateKey

- name: Cleanup join files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    #- /tmp/join-files.tar.gz
    - /tmp/join.sh
    - /tmp/certificateKey
