- name: Copy get-join-files.sh
  copy:
    src: get-join-files.sh
    dest: /tmp/get-join-files.sh
    mode: 0755

- name: Execute get-join-files.sh
  shell: /tmp/get-join-files.sh
  become: yes

- name: Fetch join-files.tar.gz
  fetch:
    src: /tmp/join-files.tar.gz
    dest: ./files/
    flat: yes

- name: Fetch join.sh
  fetch:
    src: /tmp/join.sh
    dest: ./files/
    flat: yes

- name: Cleanup join files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/join-files.tar.gz
    - /tmp/join.sh
  become: yes
