- name: copy kubeadm-config.yml
  template:
    src: kubeadm-config.yml.j2
    dest: /etc/kubernetes/kubeadm-config.yml
  become: yes

- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Init kubeadm
  include_tasks: init.yml
  when: not kubeadm_ca.stat.exists

- name: copy collect-masters.sh
  copy:
    src: collect-masters.sh
    dest: collect-masters.sh
    mode: 0755

- name: execute collect-masters.sh
  shell: ./collect-masters.sh
  become: yes

- name: Fetch masters.tar.gz
  fetch:
    src: masters.tar.gz
    dest: ./files/
    flat: yes

- name: Fetch join.sh
  fetch:
    src: masters/join.sh
    dest: ./files/
    flat: yes
