- name: copy kubeadm-config.yml
  template:
    src: kubeadm-config.yml.j2
    dest: /etc/kubernetes/kubeadm-config.yml
  become: yes

- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Execute kubeadm init
  include_tasks: init.yml
  when: not kubeadm_ca.stat.exists
