- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/admin.conf"
  register: admin_conf

- name: Execute kubeadm init
  import_tasks: init.yml
  when: not admin_conf.stat.exists
