---
### See roles/installer-defaults/main.yml for default values

## Offline install mode
offline_install: no

## kubernetes version (kubeadm, kubelet, kubectl)
kubernetes_version: 1.18.0-0

## External load balancer address.
lb_apiserver_address: 10.240.0.40   # lb defined in Vagrantfile

# Pod CIDR
pod_subnet: 192.168.0.0/16

# Firewall
#firewall_enabled: yes

# Proxy
#proxy_url: ""
#porxy_noproxy: "127.0.0.1,localhost,{{ lb_apiserver_address }}"
