- name: Copy join.sh
  copy:
    src: ./files/join.sh
    dest: /etc/kubernetes
    owner: root
    mode: 0700

#- debug:
#    msg: "certificateKey = {{ lookup('file', './files/certificateKey') }}"

- block:
    - name: Execute kubeadm join
      shell: /etc/kubernetes/join.sh --control-plane --apiserver-advertise-address {{ ip }} --node-name {{ inventory_hostname }} --certificate-key {{ lookup('file', './files/certificateKey') }} # -v 5
      register: kubeadm_join
      retries: 3
      delay: 5

    - name: Delete join.sh
      file:
        path: /etc/kubernetes/join.sh
        state: absent

  rescue:
    - name: stdout
      debug:
        var: kubeadm_join.stdout_lines

    - name: stderr
      debug:
        var: kubeadm_join.stderr_lines

    - name: Abort if kubeadm join failed
      fail:
        msg: kubeadm join failed
