- name: Extract join-files.tar.gz
  unarchive:
    src: ./files/join-files.tar.gz
    dest: /etc/kubernetes
    owner: root
  become: yes

- block:
    - name: Execute kubeadm join
      shell: /etc/kubernetes/join.sh --control-plane --apiserver-advertise-address {{ advertise_address }} -v 5
      become: yes
      register: kubeadm_join
      retries: 3
      delay: 5

  rescue:
    - name: stdout
      debug:
        var: kubeadm_join.stdout_lines

    - name: stderr
      debug:
        var: kubeadm_join.stderr_lines

    - fail:
        msg: kubeadm join failed

- name: create ~/.kube
  file:
    path: .kube/
    state: directory

- name: copy admin.conf to ~/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: .kube/config
    owner: "{{ ansible_user_id }}"
    mode: 0700
    remote_src: true
  become: yes
