- name: Copy join-files.tar.gz
  copy:
    src: ./files/join-files.tar.gz
    dest: .

- name: Extract join-files.tar.gz
  shell: tar xvzf join-files.tar.gz -C /etc/kubernetes
  become: yes

- name: Execute kubeadm join
  shell: /etc/kubernetes/join-as-master.sh
  become: yes
  register: kubeadm_join

- when: kubeadm_join|failed
  block:
    - name: stderr
      debug:
        var: kubeadm_join.stderr_lines

    - name: stdout
      debug:
        var: kubeadm_join.stdout_lines

    - fail:
        msg: kubeadm join failed

- name: create ~/.kube
  file:
    path: .kube/
    state: directory

- name: copy admin.conf to ~/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: .kube/config
    owner: "{{ ansible_user_id }}"
    mode: 0700
    remote_src: true
  become: yes
