- name: Copy masters.tar.gz
  copy:
    src: ./files/masters.tar.gz
    dest: .

- name: Extract masters.tar.gz
  shell: tar xvzf masters.tar.gz -C /etc/kubernetes
  become: yes

- name: Execute kubeadm join
  shell: /etc/kubernetes/join-as-master.sh
  become: yes
