- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Check if kubeadm has aborted
  stat:
    path: "/etc/kubernetes/join.sh"
  register: join

- name: Execute kubeadm join
  import_tasks: init.yml
  when: not kubeadm_ca.stat.exists or join.stat.exists
