- name: Create {{ calico_config_dir }} dir
  file:
    path: "{{ calico_config_dir }}"
    state: directory

- name: Copy calico cni yaml
  template:
    src: calico.yaml.j2
    dest: "{{ calico_config_dir }}/calico.yaml"

- name: Install calico cni plugin
  command: kubectl apply -f {{ calico_config_dir }}/calico.yaml --kubeconfig /etc/kubernetes/admin.conf
