- when: not offline_install
  block:
    - name: Install calico cni plugin (online mode)
      shell: curl -L {{ calico_manifest_url }} > ./calico.yaml
      environment:
        http_proxy: "{{ proxy_url }}"
        https_proxy: "{{ proxy_url }}"
        no_proxy: "{{ proxy_noproxy }}"

    - name: Install calico cni plugin (online mode)
      shell: kubectl apply -f ./calico.yaml

- name: Install calico cni plugin (offline mode)
  shell: kubectl apply -f /opt/kubernetes-offline/calico.yaml
  when: offline_install
