- name: Create /etc/kubernetes/addons/rook-ceph dir
  file:
    path: /etc/kubernetes/addons/rook-ceph
    state: directory

- name: Copy rook + ceph yamlc
  copy:
    src: "{{ item }}"
    dest: /etc/kubernetes/addons/rook-cech/
  with_items:
    - common.yaml
    - operator.yaml
    - cluster.yaml

- name: Apply rook + ceph yamls
  shell: kubectl apply -f /etc/kubernetes/addons/rook-cech/{{ item }} --kubeconfig /etc/kubernetes/admin.conf
  with_items:
    - common.yaml
    - operator.yaml
    - cluster.yaml
