- name: Unlock yum versions (backward compat)
  shell:
    cmd: yum versionlock delete kubeadm kubelet kubectl || exit 0  # need to unlock kubelet/kubectl for dependency...
    warn: false

- name: Upgrade kubeadm to {{ kubeadm_version }}
  yum:
    name: kubeadm-{{ kubeadm_version }}
    state: present
    allow_downgrade: yes
    enablerepo: "{{ yum_enablerepo }}"
    disablerepo: "{{ yum_disablerepo }}"
    disable_excludes: kubernetes

## Don't version lock kubadm/kubelet/kubectl, because kubernetes.repo excludes them.
#- name: Lock yum versions
#  shell:
#    cmd: yum versionlock add kubeadm
#    warn: false
