dependencies:
  - role: container-engine/docker
    when:
      - container_engine == "docker"

  - role: container-engine/containerd
    when:
      - container_engine == "containerd"

  - role: container-engine/cri-o
    when:
      - container_engine == "cri-o"
