- name: Set proxy in yum.conf
  lineinfile:
    path: /etc/yum.conf
    line: "proxy={{ proxy_url }}"
    regexp: "^proxy="
  when: proxy_url != ""

- name: Remove proxy in yum.conf
  lineinfile:
    path: /etc/yum.conf
    regexp: "^proxy="
    state: absent
  when: proxy_url == ""

- include_tasks: service_proxy.yml

- name: Install root certs (rhel)
  copy:
    src: "{{ item }}"
    dest: /usr/share/pki/ca-trustsource/anchors/
  with_fileglob:
    - "*.crt"
  notify:
    - update_ca_certs_rhel
