- when: proxy_url != ""
  block:
    - name: Set proxy in yum.conf
      lineinfile:
        path: /etc/yum.conf
        line: "proxy={{ proxy_url }}"
        regexp: "^proxy="

    - include_tasks: service.proxy.yml

- name: Install root certs (rhel)
  copy:
    src: "{{ item }}"
    dest: /usr/share/pki/ca-trustsource/anchors/
  with_fileglob:
    - "*.crt"
  notify:
    - update_ca_certs_rhel
