- when: proxy_url != ""
  block:
    - name: Create /etc/systemd/system/{{ container_engine }}.service.d
      file:
        path: /etc/systemd/system/{{ container_engine }}.service.d
        state: directory

    - name: Install http-proxy.conf for {{ container_engine }}
      template:
        src: http-proxy.conf.j2
        dest: /etc/systemd/system/{{ container_engine }}.service.d/http-proxy.conf

- name: Delete http-proxy.conf
  file:
    path: /etc/systemd/system/{{ container_engine }}.service.d/http-proxy.conf
    state: absent
  when: proxy_url == ""