- when: ansible_distribution in ["RedHat", "CentOS"]
  block:
    - name: Include rhel vars
      include_vars: rhel.yml
    - name: Import rhel tasks
      import_tasks: rhel.yml

- when: ansible_distribution in ["Ubuntu"]
  block:
    - name: Include ubuntu vars
      include_vars: ubuntu.yml
    - name: Import ubuntu tasks
      import_tasks: ubuntu.yml

- import_tasks: kubelet.yml

- name: Install kubectl bash completion
  shell:
    cmd: kubectl completion bash >/etc/bash_completion.d/kubectl.sh
    creates: /etc/bash_completion.d/kubectl.sh
  ignore_errors: yes

#- name: Pull images
#  command: kubeadm config images pull
#  when: not offline_install
