- include_vars: "{{ ansible_os_family }}.yml"
- include_tasks: "{{ ansible_os_family }}.yml"

- import_tasks: kubelet.yml

- name: Install kubectl bash completion
  shell:
    cmd: kubectl completion bash >/etc/bash_completion.d/kubectl.sh
    creates: /etc/bash_completion.d/kubectl.sh
  ignore_errors: yes

#- name: Pull images
#  command: kubeadm config images pull
#  when: not offline_install
