- name: Install yum-plugin-versionlock
  yum:
    name: yum-plugin-versionlock
    state: present

- name: Install kubernetes.repo
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
  when: not offline_install

- name: Unlock kubelet / kubectl / kubeadm versions
  shell: yum versionlock delete kubelet kubectl kubeadm || exit 0

- name: Install kubelet / kubectl / kubeadm
  yum:
    name:
      - kubelet-{{ kubeadm_version }}
      - kubectl-{{ kubeadm_version }}
      - kubeadm-{{ kubeadm_version }}
    state: present

- name: Lock kubelet / kubectl / kubeadm versions
  shell: yum versionlock add kubelet kubectl kubeadm

- name: Enable / start kubelet
  service:
    name: kubelet
    enabled: true
    state: started

#- name: Pull images
#  command: kubeadm config images pull
#  when: not offline_install
