- name: Install kubernetes.repo
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
  when: not offline_install

- name: Unlock kubeadm, kubelet, kubectl versions
  shell: yum versionlock delete kubelet kubectl kubeadm || exit 0

- name: Install kubeadm / kubelet / kubectl ver {{ kubeadm_version }}, etc
  yum:
    name:
      - kubeadm-{{ kubeadm_version }}
      - kubelet-{{ kubeadm_version }}
      - kubectl-{{ kubeadm_version }}
      - yum-plugin-versionlock
    state: present
    allow_downgrade: yes
    enablerepo: "{{ yum_enablerepo }}"
    disablerepo: "{{ yum_disablerepo }}"

- name: Lock kubeadm, kubelet, kubectl versions.
  shell: yum versionlock add kubelet kubectl kubeadm

- name: Enable / start kubelet
  service:
    name: kubelet
    enabled: true
    state: started

#- name: Pull images
#  command: kubeadm config images pull
#  when: not offline_install
