- when: ansible_distribution in ["RedHat", "CentOS"]
  block:
    - include_vars: rhel.yml
    - import_tasks: rhel.yml

- when: ansible_distribution in ["Ubuntu"]
  block:
    - include_vars: ubuntu.yml
    - import_tasks: ubuntu.yml

- import_tasks: kubelet.yml

- name: Install kubectl bash completion
  shell: "kubectl completion bash >/etc/bash_completion.d/kubectl.sh"
  ignore_errors: yes

#- name: Pull images
#  command: kubeadm config images pull
#  when: not offline_install
