- when: not offline_install
  block:
    - name: Copy gpg keys of kubenrnetes repo
      copy:
        src: "{{ item }}"
        dest: /tmp/
      with_items:
        - yum-key.gpg
        - rpm-package-key.gpg

    - name: Install gpg keys of kubernetes repo
      rpm_key:
        key: "{{ item }}"
        state: present
      with_items:
        - /tmp/yum-key.gpg
        - /tmp/rpm-package-key.gpg
        #- https://packages.cloud.google.com/yum/doc/yum-key.gpg
        #- https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    - name: Install kubernetes repo
      yum_repository:
        name: kubernetes
        description: Kubernetes
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgcheck: yes
        repo_gpgcheck: no

- name: Unlock kubeadm, kubelet, kubectl versions
  shell:
    cmd: yum versionlock delete kubelet kubectl kubeadm || exit 0
    warn: false

- name: Install kubeadm-{{ kubeadm_version }}, kubelet-{{ kubelet_version }} and kubectl-{{ kubectl_version }}, etc.
  yum:
    name:
      - kubeadm-{{ kubeadm_version }}
      - kubelet-{{ kubelet_version }}
      - kubectl-{{ kubectl_version }}
      - yum-plugin-versionlock
    state: present
    allow_downgrade: yes
    enablerepo: "{{ yum_enablerepo }}"
    disablerepo: "{{ yum_disablerepo }}"

- name: Lock kubeadm, kubelet, kubectl versions.
  shell:
    cmd: yum versionlock add kubelet kubectl kubeadm
    warn: false
