- when: not offline_install
  block:
    - name: Install kubernetes.repo
      copy:
        src: kubernetes.repo
        dest: /etc/yum.repos.d/kubernetes.repo

    - name: Install gpg key of kubernetes.repo
      rpm_key:
        key: "{{ item }}"
        state: present
      with_items:
        - https://packages.cloud.google.com/yum/doc/yum-key.gpg
        - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      environment: "{{ proxy_env }}"

- name: Unlock kubeadm, kubelet, kubectl versions
  shell:
    cmd: yum versionlock delete kubelet kubectl kubeadm || exit 0
    warn: false

- name: Install kubeadm-{{ kubeadm_version }}, kubelet-{{ kubelet_version }} and kubectl-{{ kubectl_version }}, etc.
  yum:
    name:
      - kubeadm-{{ kubeadm_version }}
      - kubelet-{{ kubelet_version }}
      - kubectl-{{ kubectl_version }}
      - yum-plugin-versionlock
    state: present
    allow_downgrade: yes
    enablerepo: "{{ yum_enablerepo }}"
    disablerepo: "{{ yum_disablerepo }}"

- name: Lock kubeadm, kubelet, kubectl versions.
  shell:
    cmd: yum versionlock add kubelet kubectl kubeadm
    warn: false
