- when: firewall_enabled
  block:
    - name: Install firewalld
      yum:
        name: firewalld
        state: present
        enablerepo: "{{ yum_enablerepo }}"
        disablerepo: "{{ yum_disablerepo }}"

    - name: Enable firewalld
      service:
        name: firewalld
        enabled: true
        state: started

    - name: Allow ssh
      firewalld:
        service: ssh
        permanent: yes
        state: enabled
        immediate: yes

    - name: Allow firewall for master
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      with_items:
        - 6443/tcp
        - 2379-2380/tcp
        - 10250-10252/tcp
      when: is_master

    - name: Allow firewall for worker
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      with_items:
        - 10250/tcp
        - 30000-32767/tcp
      when: is_worker

    - name: Allow firewall for calico
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      with_items:
        - 179/tcp  # BGP port
        #- 4789/udp # VXLAN

- name: Disable firewalld
  service:
    name: firewalld
    enabled: false
    state: stopped
  ignore_errors: yes
  when: not firewall_enabled