- name: Unlock yum versions
  shell:
    cmd: yum versionlock delete kubeadm || exit 0
    warn: false

- name: Update kubeadm
  yum:
    name: kubeadm-{{ kubeadm_version }}
    state: present
    enablerepo: "{{ yum_enablerepo }}"
    disablerepo: "{{ yum_disablerepo }}"

- name: Lock yum versions
  shell:
    cmd: yum versionlock add kubeadm
    warn: false
