#runc_version: v1.0.0-rc91
#runc_download_url: https://github.com/opencontainers/runc/releases/download/{{ runc_version }}/runc.amd64

containerd_version: 1.4.1
containerd_tarball: containerd-{{ containerd_version }}-linux-amd64.tar.gz
containerd_download_url: https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/{{ containerd_tarball }}

