# Calico version
calico_version: v3.14.1

# Enable IPIP?
# "Always", "CrossSubnet", "Never"
# See CALICO_IPV4POOL_IPIP option of calico.
# https://docs.projectcalico.org/reference/node/configuration
calico_ipv4pool_ipip: "Never"

# Enable VXLAN?
# "Always", "CrossSubnet", "Never"
# See CALICO_IPV4POOL_VXLAN option:
# https://docs.projectcalico.org/reference/node/configuration
calico_ipv4pool_vxlan: "Never"

# Felix iptables backend
# "Legacy", "NFT", "Auto"
# See FELIX_IPTABLESBACKEND option of calico.
# https://docs.projectcalico.org/reference/felix/configuration
calico_felix_iptablesbackend: "Auto"
