- name: Uninstall docker-ce if present
  apt:
    name: docker-ce
    state: absent

- name: Install docker.io
  apt:
    name: docker.io
    state: latest

- name: Enable / start docker
  service:
    name: docker
    enabled: true
    state: started
