- name: Force to use Docker CE for RHEL8/CentOS8
  set_fact:
    docker_ce: yes
  tags:
    - always
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"

- include_tasks: "{{ ansible_os_family }}.yml"
  when: not docker_ce

- include_tasks: "{{ ansible_os_family }}-ce.yml"
  when: docker_ce

- name: Check if /etc/docker/daemon.json exists?
  stat:
    path: /etc/docker/daemon.json
  register: st

- when: not st.stat.exists
  block:
    - name: Create /etc/docker directory
      file:
        path: /etc/docker
        state: directory

    - name: Install /etc/docker/daemon.json
      template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
        notify: restart_docker
