- name: Install / update docker
  yum:
    name: docker
    state: latest
    enablerepo: "{{ yum_enablerepo }}"
    disablerepo: "{{ yum_disablerepo }}"
  when: ansible_distribution in ["RedHat", "CentOS"]

- name: Enable / start docker
  service:
    name: docker
    enabled: true
    state: started
