- name: Check Ubuntu version
  fail:
    msg: "Only supports Ubuntu 18 / 20: current version is {{ ansible_distribution_version }}"
  when: not ansible_distribution_major_version in [ "18", "19", "20" ]
  #when: not ansible_distribution_version in [ "18.04", "20.04" ]
