- name: Check OS
  fail:
    msg: "Unsupported OS : {{ ansible_distribution }}"
  when: not ansible_distribution in ["RedHat", "CentOS", "Ubuntu"]

- name: Check RHEL/CentOS version
  fail:
    msg: "Only support ver 7.x of RHEL/CentOS"
  when: ansible_distribution in ["RedHat", "CentOS"] and ansible_distribution_major_version != "7"

- name: Check Ubuntu version
  fail:
    msg: "Only support ver 18.x of Ubuntu"
  when: ansible_distribution in ["Ubuntu"] and ansible_distribution_major_version != "18"
