- name: Make master schedulable
  shell: kubectl taint nodes {{ groups['master'] | join(' ') }} node-role.kubernetes.io/master:NoSchedule- --kubeconfig=/etc/kubernetes/admin.conf
  when: master_schedulable
  ignore_errors: yes

- name: Make master unschedulable
  shell: kubectl taint nodes {{ groups['master'] | join(' ') }} node-role.kubernetes.io/master:NoSchedule --overwrite --kubeconfig=/etc/kubernetes/admin.conf
  when: not master_schedulable

- name: Create config dir
  file:
    path: "{{ yaml_dir }}"
    state: directory

- name: Copy yaml files
  copy:
    src: "{{ item }}"
    dest: "{{ yaml_dir }}"
  with_items:
    - localstorage-sc.yml

- name: Apply kubernetes yamls
  shell: kubectl apply -f {{ yaml_dir }}/{{ item }} --kubeconfig=/etc/kubernetes/admin.conf
  with_items:
    - localstorage-sc.yml
