- name: Make master schedulable
  shell: kubectl taint nodes {{ groups['master'] | join(' ') }} node-role.kubernetes.io/master:NoSchedule- --kubeconfig=/etc/kubernetes/admin.conf
  when: master_schedulable
  ignore_errors: yes

- name: Make master unschedulable
  shell: kubectl taint nodes {{ groups['master'] | join(' ') }} node-role.kubernetes.io/master:NoSchedule --overwrite --kubeconfig=/etc/kubernetes/admin.conf
  when: not master_schedulable
