- name: Install / update docker
  yum:
    name: docker
    state: latest
    enablerepo: "{{ yum_enablerepo }}"
    disablerepo: "{{ yum_disablerepo }}"

- name: Enable / start docker
  service:
    name: docker
    enabled: true
    state: started

- name: Load container images
  shell:
    cmd: "for i in *.tar; do docker load -i $i; done"
    chdir: /opt/kubernetes-offline/images
  when: offline_install
