- hosts: master_first
  become: yes

  roles:
    - { role: installer-defaults }
    - { role: apps/metrics-server, tags: metrics-server }
    - { role: apps/helm, tags: helm }
    - { role: apps/docker-registry, tags: registry }
