- hosts: all
  become: yes

  roles:
    - { role: installer-defaults }
    - { role: preflight, tags: [common, preflight] }
    - { role: offline/prepare, tags: [common, offline] }
    - { role: setproxy, tags: [common, proxy] }
    - { role: preinstall, tags: [common, preinstall] }
    - { role: firewall, tags: [common, firewall] }
    - { role: container-engine, tags: [common, container-engine] }
    - { role: offline/load-images, tags: [common, offline] }
    - { role: k8s-packages, tags: [common, k8s-packages] }
