- hosts: master
  become: yes
  any_errors_fatal: true

  roles:
    - { role: installer-defaults }
    - { role: master/kubeadm-config, tags: kubeadm-config }
    - { role: master/certs/longer-certs }
