- hosts: master_first
  become: yes
  any_errors_fatal: true

  roles:
    - { role: installer-defaults }
    - { role: master/certs, tags: [master, master-first, certs] }
    - { role: master/first, tags: [master, master-first] }
    - { role: network-plugin/calico, tags: [master, master-first, calico] }
    - { role: master/get-join-files, tags: [master, master-first, get-join-files] }

- hosts: master_first
  become: no
  any_errors_fatal: true

  roles:
    - { role: master/install-kubeconfig, tags: [master, master-first, kubeconfig] }
