- hosts: master_secondary
  become: no
  any_errors_fatal: true
  serial: 1

  roles:
    - { role: installer-defaults }
    - { role: master/secondary, tags: [master, master-secondary] }
    - { role: master/install-kubeconfig, tags: [master, master-secondary, kubeconfig] }
