- hosts: master_first
  become: no
  any_errors_fatal: true

  roles:
    - { role: installer-defaults }
    - { role: master/first, tags: [master, master-first] }
    - { role: master/install-kubeconfig, tags: [master, master-first] }
    - { role: master/cni-plugin, tags: [master, master-first] }
    - { role: master/get-join-files, tags: [master, master-first, get-join-files] }
