# Renew all server certificates
- hosts: all
  become: yes
  serial: 1

  roles:
    - { role: installer-defaults }
    - { role: master/kubeadm-config, tags: kubeadm-config }
    - { role: ops/renew-server-certs }
