- hosts: master_first
  become: yes

  roles:
    - { role: installer-defaults }
    - { role: storage/local-storage, tags: local-storage }
    - { role: storage/rook-nfs, tags: rook-nfs }
    - { role: storage/rook-ceph, tags: rook-ceph }
    - { role: storage/default-storage-class, tags: default-storage-class }
