- hosts: worker
  become: yes

  roles:
    - installer-defaults
    - offline/prepare
    - docker
    - upgrade/upgrade-kubeadm

- hosts: worker
  become: yes
  serial: "20%"

  roles:
    - installer-defaults
    - upgrade/drain
    - upgrade/upgrade-worker
    - upgrade/uncordon

- hosts: worker
  become: yes

  roles:
    - installer-defaults
    - upgrade/upgrade-kubelet
