- hosts: master
  become: yes

  roles:
    - installer-defaults
    - upgrade/update-kubeadm

- hosts: master_first
  become: yes

  roles:
    - installer-defaults
    - upgrade/drain
    - upgrade/upgrade-master
    - upgrade/uncordon

- hosts: master_secondary
  become: yes
  serial: 1

  roles:
    - installer-defaults
    - upgrade/drain
    - upgrade/upgrade-master
    - upgrade/uncordon

- hosts: master
  become: yes

  roles:
    - installer-defaults
    - upgrade/upgrade-kubelet
