- hosts: master
  become: yes
  any_errors_fatal: true

  roles:
    - { role: installer-defaults }
    - { role: offline/prepare, tags: [common, offline] }
    - { role: container-engine/docker, tags: [common, docker] }
    - { role: offline/load-images, tags: [common, offline] }
    - { role: upgrade/upgrade-kubeadm, tags: [common, kubeadm] }

- hosts: master_first
  become: yes
  any_errors_fatal: true

  roles:
    - { role: installer-defaults }
    - { role: upgrade/drain, tags: master_first }
    - { role: upgrade/upgrade-master, tags: master_first }
    - { role: upgrade/uncordon, tags: master_first }
    - { role: network-plugin/calico, tags: [master_first, calico] }

- hosts: master_secondary
  become: yes
  any_errors_fatal: true
  serial: 1

  roles:
    - { role: installer-defaults }
    - { role: upgrade/drain, tags: master_secondary }
    - { role: upgrade/upgrade-master, tags: master_secondary }
    - { role: upgrade/uncordon, tags: master_secondary }

- hosts: master
  become: yes
  any_errors_fatal: true

  roles:
    - { role: installer-defaults }
    - { role: upgrade/upgrade-kubelet, tags: kubelet }
