- hosts: master
  become: yes
  any_errors_fatal: true

  roles:
    - installer-defaults
    - offline/prepare
    - container-engine/docker
    - offline/load-images
    - upgrade/upgrade-kubeadm

- hosts: master_first
  become: yes
  any_errors_fatal: true

  roles:
    - installer-defaults
    - upgrade/drain
    - upgrade/upgrade-master
    - upgrade/uncordon
    - network-plugin/calico

- hosts: master_secondary
  become: yes
  any_errors_fatal: true
  serial: 1

  roles:
    - installer-defaults
    - upgrade/drain
    - upgrade/upgrade-master
    - upgrade/uncordon

- hosts: master
  become: yes
  any_errors_fatal: true

  roles:
    - installer-defaults
    - upgrade/upgrade-kubelet
