- hosts: worker
  become: yes

  roles:
    - { role: installer-defaults }
    - { role: offline/prepare, tags: [common, offline] }
    - { role: container-engine, tags: [common, container-engine] }
    - { role: offline/load-images, tags: [common, offline] }
    - { role: upgrade/upgrade-kubeadm, tags: [common, kubeadm] }

- hosts: worker
  become: yes
  serial: "20%"

  roles:
    - { role: installer-defaults }
    - { role: upgrade/drain }
    - { role: upgrade/upgrade-worker }
    - { role: upgrade/uncordon }

- hosts: worker
  become: yes

  roles:
    - { role: installer-defaults }
    - { role: upgrade/upgrade-kubelet, tags: kubelet }
