- hosts: worker
  become: yes
  serial: "20%"

  roles:
    - installer-defaults
    - offline
    - docker
    - upgrade/update-kubeadm
    - upgrade/drain
    - upgrade/upgrade-worker
    - upgrade/uncordon
    - upgrade/upgrade-kubelet
