- name: Copy join.sh
  copy:
    src: ./files/join.sh
    dest: /etc/kubernetes/
    mode: 0700

- name: Set default --cri-socket option
  set_fact:
    crisocket_flag: ""

- name: Set --cri-socket option for containerd
  set_fact:
    crisocket_flag: --cri-socket /run/containerd/containerd.sock
  when: container_engine == "containerd"

- block:
    - name: Execute kubeadm join
      shell: /etc/kubernetes/join.sh --node-name {{ inventory_hostname }} {{ crisocket_flag }} # -v 5
      # ignore_errors: yes
      register: kubeadm_join

    - name: Delete join.sh
      file:
        path: /etc/kubernetes/join.sh
        state: absent

  rescue:
    - name: stderr
      debug:
        var: kubeadm_join.stderr_lines

    - name: stdout
      debug:
        var: kubeadm_join.stdout_lines

    - name: Abort if kubeadm join failed
      fail:
        msg: kubeadm join failed
