- name: Copy join.sh
  copy:
    src: ./files/join.sh
    dest: .
    mode: 0700

- block:
    - name: Execute kubeadm join
      shell: ./join.sh --node-name {{ inventory_hostname }} # -v 5
      become: yes
      ignore_errors: yes
      register: kubeadm_join

  rescue:
    - name: stderr
      debug:
        var: kubeadm_join.stderr_lines

    - name: stdout
      debug:
        var: kubeadm_join.stdout_lines

    - fail:
        msg: kubeadm join failed
