- name: Check if kubeadm join has already run
  stat:
    path: "/etc/kubernetes/kubelet.conf"
  register: kubelet_conf

- name: Check if kubeadm join has aborted
  stat:
    path: "/etc/kubernetes/join.sh"
  register: join

- name: Execute kubeadm join
  import_tasks: join.yml
  when: not kubelet_conf.stat.exists or join.stat.exists
