- name: Create dir for nfs local volume on {{ rook_nfs_pv_host }}
  file:
    path: "{{ rook_nfs_pv_dir }}"
    state: directory
  delegate_to: "{{ rook_nfs_pv_host }}"

- name: Create nfs yaml dir
  file:
    path: "{{ yaml_dir }}"
    state: directory

- name: Copy yaml files
  copy:
    src: "{{ item }}"
    dest: "{{ yaml_dir }}"
  with_items:
    - namespace.yml
    - rook/common.yaml
    - rook/operator.yaml
    #- rook/provisioner.yaml

- name: Copy yaml templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ yaml_dir }}/{{ item }}"
  with_items:
    - nfs-local-pv.yml
    - nfs-server.yml

- name: Apply kubernetes yamls
  shell: kubectl apply -f {{ yaml_dir }}/{{ item }} --kubeconfig=/etc/kubernetes/admin.conf
  with_items:
    - namespace.yml
    - nfs-local-pv.yml
    - common.yaml
    - operator.yaml
    #- provisioner.yaml
    - nfs-server.yml
