- name: Sign and generate {{ basename }} cert
  shell:
    cmd: >-
      /usr/local/bin/cfssl sign
      -config ../config/ca-config.json
      -profile {{ profile }}
      -ca ../{{ ca }}.crt
      -ca-key ../{{ ca }}.key
      {{ basename }}.csr
      | /usr/local/bin/cfssljson -bare {{ basename }}
    chdir: /etc/kubernetes/pki/csr

- name: Rename cert
  shell:
    cmd: /bin/mv {{ basename }}.pem {{ basename }}.crt
    chdir: /etc/kubernetes/pki/csr
