- name: Install python cryptography
  yum:
    name:
      - python2-cryptography
      #- python36-cryptography
    state: present
    enablerepo: "{{ yum_enablerepo }}"
    disablerepo: "{{ yum_disablerepo }}"
