- name: Create registry namespace
  shell: kubectl get namespace registry --kubeconfig /etc/kubernetes/admin.conf || kubectl create namespace registry --kubeconfig /etc/kubernetes/admin.conf

- name: Create {{ registry_config_dir }} dir
  file:
    path: "{{ registry_config_dir }}"
    state: directory

# Create htpasswd
# Note: do not use ansible htpassword module
- name: Create htpasswd
  shell:
    cmd: docker run --rm --entrypoint htpasswd registry:{{ registry_version }} -Bbn {{ registry_user }} {{ registry_password }} > htpasswd
    chdir: "{{ registry_config_dir }}"

- name: Change htpasswd mode
  file:
    path: "{{ registry_config_dir }}/htpasswd"
    owner: root
    mode: 0600

- name: Copy registry.csr json
  copy:
    src: registry.csr.json
    dest: "{{ registry_config_dir }}/"

- name: Create certificates
  shell:
    cmd: >-
      /usr/local/bin/cfssl gencert
      -ca /etc/kubernetes/pki/ca.crt
      -ca-key /etc/kubernetes/pki/ca.key
      -cn registry
      -hostname localhost,127.0.0.1,{{ inventory_hostname }}
      registry.csr.json
      | /usr/local/bin/cfssljson -bare registry
    chdir: "{{ registry_config_dir }}"

- name: Rename certificate
  shell:
    cmd: "{{ item }}"
    chdir: "{{ registry_config_dir }}"
  with_items:
    - /bin/mv registry-key.pem registry.key
    - /bin/mv registry.pem registry.crt

- import_tasks: static-pod.yml
  when: registry_type == "static-pod"