- name: metrics-server | Create dir
  file:
    path: /etc/kubernetes/addons/metrics-server
    state: directory
    owner: root
    group: root
    mode: 0755

- name: metrics-server | Create manifests
  copy:
    src: components.yaml
    dest: /etc/kubernetes/addons/metrics-server/

- name: metrics-server | Apply manifests
  command: kubectl apply -f /etc/kubernetes/addons/metrics-server/components.yaml --kubeconfig /etc/kubernetes/admin.conf
