- when: inventory_hostname in groups["master_first"]
  block:
    - block:
        - name: Execute kubeadm upgrade plan to {{ kube_version }}
          shell: kubeadm upgrade plan {{ kube_version }}
          register: kubeadm_upgrade
          #environment:
          #  http_proxy: "{{ proxy_url }}"
          #  https_proxy: "{{ proxy_url }}"
          #  no_proxy: "{{ proxy_noproxy }}"

      always:
        - name: stdout
          debug:
            var: kubeadm_upgrade.stdout_lines

        - name: stderr
          debug:
            var: kubeadm_upgrade.stderr_lines

    - block:
        - name: Upgrade first master to {{ kube_version }}
          shell: kubeadm upgrade apply {{ kube_version }} -y -v 5
          register: kubeadm_upgrade

      always:
        - name: stdout
          debug:
            var: kubeadm_upgrade.stdout_lines

        - name: stderr
          debug:
            var: kubeadm_upgrade.stderr_lines

- when: inventory_hostname in groups["master_secondary"]
  block:
    - name: Upgrade secondary masters to {{ kube_version }}
      shell: kubeadm upgrade node
