- when: inventory_hostname in groups["master_first"]
  block:
    - block:
        - name: Execute kubeadm upgrade plan to {{ kube_version }}
          shell: kubeadm upgrade plan v{{ kube_version }}
          register: kubeadm_upgrade
          tags:
            - upgrade-plan
          #environment: "{{ proxy_env }}"

      always:
        - name: stdout
          debug:
            var: kubeadm_upgrade.stdout_lines
          tags:
            - upgrade-plan

        - name: stderr
          debug:
            var: kubeadm_upgrade.stderr_lines
          tags:
            - upgrade-plan

    - block:
        - name: Upgrade first master to {{ kube_version }}
          shell: kubeadm upgrade apply v{{ kube_version }} -y -v 5
          register: kubeadm_upgrade

      always:
        - name: stdout
          debug:
            var: kubeadm_upgrade.stdout_lines

        - name: stderr
          debug:
            var: kubeadm_upgrade.stderr_lines

- when: inventory_hostname in groups["master_secondary"]
  block:
    - name: Upgrade secondary masters to v{{ kube_version }}
      shell: kubeadm upgrade node
