- when: inventory_hostname in groups["master_first"]
  block:
    - name: Execute kubeadm upgrade plan to {{ kube_version }}
      shell: kubeadm upgrade plan {{ kube_version }}
      register: kubeadm_upgrade
      ignore_errors: yes
      #environment:
      #  http_proxy: "{{ proxy_url }}"
      #  https_proxy: "{{ proxy_url }}"
      #  no_proxy: "{{ proxy_noproxy }}"

    - name: stdout
      debug:
        var: kubeadm_upgrade.stdout_lines

    - name: stderr
      debug:
        var: kubeadm_upgrade.stderr_lines

    - fail:
        msg: kubeadm upgrade plan failed
      when: kubeadm_upgrade is failed


    - name: Upgrade first master to {{ kube_version }}
      shell: kubeadm upgrade apply {{ kube_version }} -y
      ignore_errors: yes
      register: kubeadm_upgrade

    - when: kubeadm_upgrade is failed
      block:
        - name: stdout
          debug:
            var: kubeadm_upgrade.stdout_lines

        - name: stderr
          debug:
            var: kubeadm_upgrade.stderr_lines

        - fail:
            msg: kubeadm upgrade failed

- when: inventory_hostname in groups["master_secondary"]
  block:
    - name: Upgrade secondary masters to {{ kube_version }}
      shell: kubeadm upgrade node
