- name: Check if {{ basename }}.crt exists?
  stat:
    path: /etc/kubernetes/pki/{{ basename }}.crt
  register: st

- when: not st.stat.exists
  block:
    - name: Generate {{ basename }} key
      openssl_privatekey:
        path: /etc/kubernetes/pki/{{ basename }}.key
        size: 2048
        mode: 0600
        #owner: root

    - name: Generate {{ basename }} csr
      openssl_csr:
        path: /etc/kubernetes/pki/{{ basename }}.csr
        privatekey_path: /etc/kubernetes/pki/{{ basename }}.key
        common_name:  "{{ cn }}"
        basic_constraints:
          - "CA:TRUE"
        #basic_constraints_critical: yes
        key_usage:
          - keyCertSign
          - cRLSign
          - digitalSignature
        #extended_key_usage_critical: yes

    - name: Generate {{ basename }} cert
      openssl_certificate:
        path: /etc/kubernetes/pki/{{ basename }}.crt
        privatekey_path: /etc/kubernetes/pki/{{ basename }}.key
        csr_path: /etc/kubernetes/pki/{{ basename }}.csr
        provider: selfsigned
        selfsigned_not_after: "{{ ca_not_after }}"

    - name: Delete {{ basename }} csr
      file:
        path: /etc/kubernetes/pki/{{ basename }}.csr
        state: absent
