- name: Check if {{ basename }}.crt exists?
  stat:
    path: /etc/kubernetes/pki/{{ basename }}.crt
  register: st

- when: not st.stat.exists
  block:
    - name: Generate {{ basename }} csr json
      template:
        src: ca-csr.json.j2
        dest: /etc/kubernetes/pki/{{ basename }}-csr.json

    - name: Generate {{ basename }} certs
      shell:
        cmd: /usr/local/bin/cfssl gencert -initca /etc/kubernetes/pki/{{ basename }}-csr.json | /usr/local/bin/cfssljson -bare {{ basename }}
        chdir: /etc/kubernetes/pki

    - name: Move {{ basename }} key
      shell: /bin/mv /etc/kubernetes/pki/{{ basename }}-key.pem /etc/kubernetes/pki/{{ basename }}.key

    - name: Move {{ basename }} cert
      shell: /bin/mv /etc/kubernetes/pki/{{ basename }}.pem /etc/kubernetes/pki/{{ basename }}.crt

    - name: Delete csr
      file:
        path: /etc/kubernetes/pki/{{ item }}
        state: absent
      with_items:
        - "{{ basename }}-csr.json"
        - "{{ basename }}.csr"
