- file:
    path: "{{ role_path }}/files/etcd"
    state: directory
  delegate_to: localhost
  become: no

- import_tasks: ca.yml
  vars:
    basename: ca
    cn: kubernetes

- import_tasks: ca.yml
  vars:
    basename: etcd/ca
    cn: etcd-ca

- import_tasks: ca.yml
  vars:
    basename: front-proxy-ca
    cn: front-proxy-ca
