- name: Create pki dir
  file:
    path: /etc/kubernetes/pki/{{ item }}
    state: directory
    owner: root
    mode: 0755
  with_items:
    - etcd
    - config

- name: Create ca config json for cfssl
  template:
    src: ca-config.json.j2
    dest: /etc/kubernetes/pki/config/ca-config.json

- import_tasks: ca.yml
  vars:
    basename: ca
    cn: kubernetes

- import_tasks: ca.yml
  vars:
    basename: etcd/ca
    cn: etcd-ca

- import_tasks: ca.yml
  vars:
    basename: front-proxy-ca
    cn: front-proxy-ca
