- include_tasks: "{{ ansible_os_family }}.yml"

#- name: Install containerd config.toml
#  copy:
#    src: config.toml
#    dest: /etc/containerd/config.toml

- name: Create /etc/containerd dir
  file:
    path: /etc/containerd
    state: directory

- name: Install containerd config.toml
  copy:
    src: config.toml
    dest: /etc/containerd/config.toml

#- name: Install containerd unit file
#  copy:
#    src: containerd.service
#    dest: /etc/systemd/system/containerd.service

- name: Enable containerd service
  systemd:
    name: containerd
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Install crictl.yaml
  copy:
    src: crictl.yaml
    dest: /etc
