- name: Unlock yum versions
  shell:
    cmd: yum versionlock delete kubelet kubectl || exit 0
    warn: false

- name: Update kubelet and kubectl
  yum:
    name:
      - kubelet-{{ kubeadm_version }}
      - kubectl-{{ kubeadm_version }}
    state: present
    enablerepo: "{{ yum_enablerepo }}"
    disablerepo: "{{ yum_disablerepo }}"

- name: Restart kubelet
  service:
    name: kubelet
    state: restarted

- name: Lock yum versions
  shell:
    cmd: yum versionlock add kubelet kubectl
    warn: false
