- name: Unlock yum versions
  shell: yum versionlock delete kubelet kubectl || exit 0

- name: Update kubelet and kubectl
  yum:
    name:
      - kubelet-{{ kubeadm_version }}
      - kubectl-{{ kubeadm_version }}
    state: present
    enablerepo: "{{ yum_enablerepo }}"
    disablerepo: "{{ yum_disablerepo }}"

- name: Restart kubelet
  service:
    name: kubelet
    state: restarted

- name: Lock yum versions
  shell: yum versionlock add kubelet kubectl
