- name: Unlock yum versions
  shell:
    cmd: yum versionlock delete kubelet kubectl || exit 0
    warn: false

- name: Update kubelet {{ kubelet_version }} and kubectl {{ kubectl_version }}
  yum:
    name:
      - kubelet-{{ kubelet_version }}
      - kubectl-{{ kubectl_version }}
    state: present
    enablerepo: "{{ yum_enablerepo }}"
    disablerepo: "{{ yum_disablerepo }}"
    disable_excludes: kubernetes

- name: Lock yum versions
  shell:
    cmd: yum versionlock add kubelet kubectl
    warn: false
